<?php

declare(strict_types=1);

class BayrolDiscovery extends IPSModule
{
    private const STATUS_ACTIVE=102, STATUS_STORAGE_ERROR=202, STATUS_API_ERROR=203, SCHEMA_VERSION=6;
    /** Object IDs published in the BAYROL PM5 Modbus-XML protocol specification. */
    private const DOCUMENTED_OBJECT_IDS=[
        34=>[3001,3002,3003,3017,3018,3019,3049,3050,3051,3052,3053,3054,3069,3070,3074,3075,3079,3080,3084,4001,4008,4022,4033,4047,4069,4071,4077],
        44=>[2001,2002,2003,2004,2005,2006,2009,2010,2011,2012,2013,2014,2019,2020,2021,2022,2023,2024,2025,2028,2029,2030,2031,2032,2033,2034,2035,2036,2037,2038,2039]
    ];
    private const CSV_FILES=[
        'meta'=>['key','value'],
        'scans'=>['scan_id','started_at','finished_at','host','port','generated_keys','found_keys','duration_ms','notes'],
        'api_keys'=>['api_key','current_value','detected_value_type','value_type','type_override','semantic_type','profile_override','unit_override','confidence','suggested_name','is_favorite','first_seen','last_seen','last_scan_id','comment','gateway_variable_name','gateway_import_enabled'],
        'observations'=>['scan_id','api_key','value','value_type','observed_at'],
        'devices'=>['code','name','device_type','confidence','status_key','value_key','first_seen','last_seen'],
        'device_keys'=>['device_code','api_key','role','is_required','direction','assignment_source'],
        'tags'=>['name','color','description'],'key_tags'=>['api_key','tag']
    ];

    public function Create(){parent::Create();foreach([['Host','192.168.55.23'],['ScanSuffixes','value;status;opmode;text1;text2'],['SelectedApiKey',''],['SelectedApiKeyComment',''],['SelectedGatewayVariableName',''],['SelectedDeviceCode',''],['ManualDeviceCode',''],['ManualDeviceName',''],['ManualDeviceType','sensor_group'],['ManualDeviceRole','measurement']] as $p)$this->RegisterPropertyString($p[0],$p[1]);foreach([['Port',80],['Timeout',10],['ScanGroupStart',34],['ScanGroupEnd',55],['ScanObjectStart',4000],['ScanObjectEnd',17200],['ScanMaxKeys',500],['ScanBatchSize',50]] as $p)$this->RegisterPropertyInteger($p[0],$p[1]);$this->RegisterPropertyBoolean('DebugMode',false);$this->RegisterPropertyBoolean('KeepDatabaseOnDelete',true);}
    public function ApplyChanges(){parent::ApplyChanges();$this->RegisterVariables();try{$this->InitializeStorage();$this->SetValueSafe('StorageReady',true);$this->SetValueSafe('StorageStatus','CSV Storage bereit. Schema v'.self::SCHEMA_VERSION);$this->SetValueSafe('StoragePath',$this->GetStorageDirectory());$this->SetValueSafe('StorageSchemaVersion',self::SCHEMA_VERSION);$this->SetValueSafe('ScanSummary',$this->BuildScanSummary());$this->SetStatus(self::STATUS_ACTIVE);}catch(Throwable $e){$this->SetValueSafe('StorageReady',false);$this->SetValueSafe('StorageStatus',$e->getMessage());$this->SetStatus(self::STATUS_STORAGE_ERROR);}}

    public function GetConfigurationForm(){return json_encode(['elements'=>$this->GetConfigurationElements(),'actions'=>$this->GetConfigurationActions(),'status'=>[['code'=>self::STATUS_ACTIVE,'icon'=>'active','caption'=>'CSV Storage bereit'],['code'=>self::STATUS_STORAGE_ERROR,'icon'=>'error','caption'=>'CSV Storage Fehler'],['code'=>self::STATUS_API_ERROR,'icon'=>'error','caption'=>'PM5 API Fehler']]]);}

    private function GetConfigurationElements():array{return[
        ['type'=>'Label','caption'=>'Verbindung'],
        ['type'=>'ValidationTextBox','name'=>'Host','caption'=>'PoolManager IP / Host'],['type'=>'NumberSpinner','name'=>'Port','caption'=>'Port','minimum'=>1,'maximum'=>65535],['type'=>'NumberSpinner','name'=>'Timeout','caption'=>'HTTP Timeout in Sekunden','minimum'=>1,'maximum'=>120],['type'=>'CheckBox','name'=>'DebugMode','caption'=>'Erweiterte Debug-Ausgaben'],
        ['type'=>'Label','caption'=>'Scan-Bereich'],
        ['type'=>'Label','caption'=>'Die Gruppen 34 und 44 verwenden ausschliesslich die offiziell dokumentierten Objekt-IDs. Die Objekt-ID-Grenzen gelten nur fuer andere Gruppen.'],
        ['type'=>'NumberSpinner','name'=>'ScanGroupStart','caption'=>'Gruppe von','minimum'=>1,'maximum'=>999],['type'=>'NumberSpinner','name'=>'ScanGroupEnd','caption'=>'Gruppe bis','minimum'=>1,'maximum'=>999],['type'=>'NumberSpinner','name'=>'ScanObjectStart','caption'=>'Objekt-ID von (andere Gruppen)','minimum'=>1,'maximum'=>99999],['type'=>'NumberSpinner','name'=>'ScanObjectEnd','caption'=>'Objekt-ID bis (andere Gruppen)','minimum'=>1,'maximum'=>99999],['type'=>'ValidationTextBox','name'=>'ScanSuffixes','caption'=>'Suffixe'],['type'=>'NumberSpinner','name'=>'ScanMaxKeys','caption'=>'Maximale Keys pro Scan','minimum'=>1,'maximum'=>5000],['type'=>'NumberSpinner','name'=>'ScanBatchSize','caption'=>'Batchgroesse','minimum'=>1,'maximum'=>100],
        ['type'=>'Label','caption'=>'Datenspeicherung'],
        ['type'=>'CheckBox','name'=>'KeepDatabaseOnDelete','caption'=>'CSV-Dateien bei Instanzloeschung behalten'],['type'=>'Label','caption'=>'CSV-Pfad: '.$this->GetStorageDirectory()]
    ];}

    private function GetConfigurationActions():array{return[
            ['type'=>'Label','caption'=>'Scan und Status'],
            ['type'=>'Button','caption'=>'Verbindung testen','onClick'=>'echo BPD_TestConnection($id);'],['type'=>'Button','caption'=>'CSV Storage pruefen','onClick'=>'echo BPD_CheckDatabase($id);'],['type'=>'Button','caption'=>'Scan starten','onClick'=>'echo BPD_RunScan($id);'],['type'=>'Button','caption'=>'Scan-Zusammenfassung laden','onClick'=>'echo BPD_GetScanSummary($id);'],
            ['type'=>'Label','caption'=>'API-Key Browser'],
            ['type'=>'Button','caption'=>'Browser laden','onClick'=>'echo BPD_LoadBrowser($id);'],$this->GetApiKeyListDefinition(),
            ['type'=>'Button','caption'=>'Markierten API-Key testen','onClick'=>'echo BPD_TestApiKeyFor($id,(string)($BrowserList["api_key"]??""));'],['type'=>'Button','caption'=>'Details laden','onClick'=>'echo BPD_LoadApiKeyDetailsFor($id,(string)($BrowserList["api_key"]??""));'],['type'=>'Button','caption'=>'Gateway-Import umschalten','onClick'=>'echo BPD_ToggleGatewayImportFor($id,(string)($BrowserList["api_key"]??""));'],['type'=>'Button','caption'=>'Favorit umschalten','onClick'=>'echo BPD_ToggleFavoriteFor($id,(string)($BrowserList["api_key"]??""));'],
            ['type'=>'ValidationTextBox','name'=>'SelectedApiKeyComment','caption'=>'Kommentar'],['type'=>'Button','caption'=>'Kommentar speichern','onClick'=>'echo BPD_SaveApiKeyCommentFor($id,(string)($BrowserList["api_key"]??""),(string)$SelectedApiKeyComment);'],['type'=>'ValidationTextBox','name'=>'SelectedGatewayVariableName','caption'=>'Gateway-Variablenname'],['type'=>'Button','caption'=>'Variablenname speichern','onClick'=>'echo BPD_SaveGatewayVariableNameFor($id,(string)($BrowserList["api_key"]??""),(string)$SelectedGatewayVariableName);'],
            ['type'=>'Label','caption'=>'Typ-Override: auto, boolean, integer, float, string oder enum.'],['type'=>'ValidationTextBox','name'=>'ApiKeyTypeOverride','caption'=>'Effektiver Typ'],['type'=>'ValidationTextBox','name'=>'ApiKeySemanticType','caption'=>'Semantik'],['type'=>'ValidationTextBox','name'=>'ApiKeyProfileOverride','caption'=>'Profil optional'],['type'=>'ValidationTextBox','name'=>'ApiKeyUnitOverride','caption'=>'Einheit optional'],['type'=>'Button','caption'=>'Typ/Semantik speichern','onClick'=>'echo BPD_SaveApiKeyMetadataFor($id,(string)($BrowserList["api_key"]??""),(string)$ApiKeyTypeOverride,(string)$ApiKeySemanticType,(string)$ApiKeyProfileOverride,(string)$ApiKeyUnitOverride);'],
            ['type'=>'Label','caption'=>'Device-Zuordnung'],
            ['type'=>'ValidationTextBox','name'=>'ManualDeviceCode','caption'=>'Device-Code'],['type'=>'ValidationTextBox','name'=>'ManualDeviceName','caption'=>'Device-Name'],['type'=>'ValidationTextBox','name'=>'ManualDeviceType','caption'=>'Device-Typ'],['type'=>'ValidationTextBox','name'=>'ManualDeviceRole','caption'=>'Rolle'],['type'=>'Button','caption'=>'Markierten API-Key zuordnen','onClick'=>'echo BPD_AssignApiKeyToDeviceFor($id,(string)($BrowserList["api_key"]??""),(string)$ManualDeviceCode,(string)$ManualDeviceName,(string)$ManualDeviceType,(string)$ManualDeviceRole);'],
            ['type'=>'Button','caption'=>'Device Browser laden','onClick'=>'echo BPD_LoadDevices($id);'],$this->GetDeviceListDefinition(),['type'=>'ValidationTextBox','name'=>'DeviceFamilyStatusKey','caption'=>'Status-Key'],['type'=>'Button','caption'=>'Device-Familie suchen','onClick'=>'echo BPD_DiscoverDeviceFamilyFor($id,(string)($DeviceList["code"]??""),(string)$DeviceFamilyStatusKey);'],['type'=>'NumberSpinner','name'=>'DeviceNeighborRadius','caption'=>'Nachbarschafts-Radius Objekt-IDs','value'=>2,'minimum'=>1,'maximum'=>5],['type'=>'Button','caption'=>'Device-Nachbarschaft scannen','onClick'=>'echo BPD_DiscoverDeviceNeighborsFor($id,(string)($DeviceList["code"]??""),(string)$DeviceFamilyStatusKey,(int)$DeviceNeighborRadius);'],['type'=>'Button','caption'=>'Device Details laden','onClick'=>'echo BPD_LoadDeviceDetailsFor($id,(string)($DeviceList["code"]??""));'],['type'=>'Button','caption'=>'Device Export-Vorschau','onClick'=>'echo BPD_PreviewDeviceExportFor($id,(string)($DeviceList["code"]??""));']
    ];}

    public function CheckDatabase():string{try{$this->InitializeStorage();$m='CSV Storage OK. API-Keys: '.count($this->ReadCsvAssoc('api_keys')).', Scans: '.count($this->ReadCsvAssoc('scans')).', Observations: '.count($this->ReadCsvAssoc('observations')).', Devices: '.count($this->ReadCsvAssoc('devices')).', Schema: v'.self::SCHEMA_VERSION;$this->SetValueSafe('StorageStatus',$m);return $m;}catch(Throwable $e){return 'CSV-Fehler: '.$e->getMessage();}}
    public function TestConnection():string{try{$r=$this->ApiGet(['34.4001.value']);return isset($r['data']['34.4001.value'])?'Verbindung OK. pH-Key empfangen.':'Verbindung OK, aber pH-Key nicht enthalten.';}catch(Throwable $e){return 'Verbindungsfehler: '.$e->getMessage();}}
    public function TestApiKeyFor(string $key):string{$key=trim($key);if($key==='')return'Keine Browser-Zeile ausgewaehlt.';try{$r=$this->ApiGet([$key]);if(!array_key_exists($key,$r['data']??[]))return'API-Key nicht in Antwort enthalten: '.$key;$v=$this->CleanString((string)$r['data'][$key]);$d=$this->DetectValueType($v);$a=$this->IndexBy($this->ReadCsvAssoc('api_keys'),'api_key');$a[$key]=$this->MergeApiKeyObservation($key,$v,$d,$a[$key]??[],date('Y-m-d H:i:s'),'');$this->WriteCsvAssoc('api_keys',array_values($a));$this->UpdateBrowserFormList($this->BuildBrowserRows());return'API-Key getestet: '.$key.' | Wert: '.$v.' | erkannt: '.$d.' | effektiv: '.$a[$key]['value_type'];}catch(Throwable $e){return'API-Key Testfehler: '.$e->getMessage();}}

    public function RunScan():string{try{$this->InitializeStorage();$keys=$this->BuildScanKeys();$sid=$this->GetNextScanId();$now=date('Y-m-d H:i:s');$api=$this->IndexBy($this->ReadCsvAssoc('api_keys'),'api_key');$dev=$this->IndexBy($this->ReadCsvAssoc('devices'),'code');$dk=$this->ReadCsvAssoc('device_keys');$obs=[];$found=0;$dur=0;foreach(array_chunk($keys,max(1,min(100,$this->ReadPropertyInteger('ScanBatchSize'))))as$c){$r=$this->ApiGet($c);$dur+=(int)($r['_meta']['duration_ms']??0);foreach(($r['data']??[])as$k=>$v){$v=$this->CleanString((string)$v);if($v==='')continue;$d=$this->DetectValueType($v);$api[$k]=$this->MergeApiKeyObservation((string)$k,$v,$d,$api[$k]??[],$now,(string)$sid);$obs[]=['scan_id'=>(string)$sid,'api_key'=>(string)$k,'value'=>$v,'value_type'=>$d,'observed_at'=>$now];$this->ClassifyDevice((string)$k,$now,$dev,$dk);$found++;}}$this->WriteCsvAssoc('api_keys',array_values($api));$this->AppendCsvAssoc('observations',$obs);$this->WriteCsvAssoc('devices',array_values($dev));$this->WriteCsvAssoc('device_keys',$this->UniqueRows($dk,['device_code','api_key']));$fin=date('Y-m-d H:i:s');$this->AppendCsvAssoc('scans',[['scan_id'=>(string)$sid,'started_at'=>$now,'finished_at'=>$fin,'host'=>$this->ReadPropertyString('Host'),'port'=>(string)$this->ReadPropertyInteger('Port'),'generated_keys'=>(string)count($keys),'found_keys'=>(string)$found,'duration_ms'=>(string)$dur,'notes'=>'CSV scan']]);$this->SetValueSafe('LastScanId',$sid);$this->SetValueSafe('LastScanGeneratedKeys',count($keys));$this->SetValueSafe('LastScanFoundKeys',$found);$this->SetValueSafe('LastResponseTimeMs',$dur);$this->SetValueSafe('ScanSummary',$this->BuildScanSummary());$this->UpdateBrowserFormList($this->BuildBrowserRows());$this->UpdateDeviceFormList($this->BuildDeviceRows());return'Scan abgeschlossen. Scan-ID: '.$sid.', erzeugte Keys: '.count($keys).', gefunden: '.$found.', Dauer API: '.$dur.' ms';}catch(Throwable $e){return'Scan-Fehler: '.$e->getMessage();}}
    public function GetScanSummary():string{$m=$this->BuildScanSummary();$this->SetValueSafe('ScanSummary',$m);return$m;}
    public function LoadBrowser():string{$r=$this->BuildBrowserRows();$this->UpdateBrowserFormList($r);return'API-Key Browser geladen. Zeilen: '.count($r);}
    public function LoadDevices():string{$r=$this->BuildDeviceRows();$this->UpdateDeviceFormList($r);return'Device Browser geladen. Devices: '.count($r);}
    public function DiscoverDeviceFamilyFor(string $c,string $s):string{return$this->DiscoverDeviceRangeFor($c,$s,0);}public function DiscoverDeviceNeighborsFor(string $c,string $s,int $r):string{return$this->DiscoverDeviceRangeFor($c,$s,max(1,min(5,$r)));}

    public function LoadApiKeyDetailsFor(string $key):string{$key=trim($key);$a=$this->IndexBy($this->ReadCsvAssoc('api_keys'),'api_key');if($key===''||!isset($a[$key]))return'API-Key nicht gefunden: '.$key;$r=$a[$key];$d='API-Key: '.$key."\nDevice: ".$this->GetDeviceForApiKey($key)."\nWert: ".($r['current_value']??'')."\nErkannter Typ: ".($r['detected_value_type']??'')."\nEffektiver Typ: ".($r['value_type']??'')."\nTyp-Override: ".($r['type_override']??'auto')."\nSemantik: ".($r['semantic_type']??'')."\nProfil: ".($r['profile_override']??'')."\nEinheit: ".($r['unit_override']??'')."\nGateway-Import: ".(($r['gateway_import_enabled']??'0')==='1'?'ja':'nein')."\nKommentar: ".($r['comment']??'');$this->SetValueSafe('SelectedApiKeyDetails',$d);return$d;}
    public function SaveApiKeyMetadataFor(string $key,string $t,string $s,string $p,string $u):string{$key=trim($key);$t=strtolower(trim($t));if($t==='')$t='auto';if(!in_array($t,['auto','boolean','integer','float','string','enum'],true))return'Ungueltiger Typ. Erlaubt: auto, boolean, integer, float, string, enum.';$a=$this->IndexBy($this->ReadCsvAssoc('api_keys'),'api_key');if(!isset($a[$key]))return'API-Key nicht gefunden: '.$key;$d=(string)($a[$key]['detected_value_type']??$a[$key]['value_type']??'string');$a[$key]['type_override']=$t;$a[$key]['value_type']=$this->ResolveEffectiveType($d,$t);$a[$key]['semantic_type']=trim($s);$a[$key]['profile_override']=trim($p);$a[$key]['unit_override']=trim($u);$this->WriteCsvAssoc('api_keys',array_values($a));$this->UpdateBrowserFormList($this->BuildBrowserRows());return'Typ/Semantik gespeichert: '.$key.' | erkannt: '.$d.' | effektiv: '.$a[$key]['value_type'].'.';}
    public function SaveApiKeyCommentFor(string $key,string $c):string{return$this->UpdateApiKeyField($key,'comment',trim($c),'Kommentar gespeichert: ');}
    public function SaveGatewayVariableNameFor(string $key,string $n):string{return$this->UpdateApiKeyField($key,'gateway_variable_name',trim($n),'Gateway-Variablenname gespeichert: ');}
    public function ToggleGatewayImportFor(string $key):string{$a=$this->IndexBy($this->ReadCsvAssoc('api_keys'),'api_key');if(!isset($a[$key]))return'API-Key nicht gefunden: '.$key;$a[$key]['gateway_import_enabled']=($a[$key]['gateway_import_enabled']??'0')==='1'?'0':'1';$this->WriteCsvAssoc('api_keys',array_values($a));$this->UpdateBrowserFormList($this->BuildBrowserRows());$this->UpdateDeviceFormList($this->BuildDeviceRows());return'Gateway-Import '.($a[$key]['gateway_import_enabled']==='1'?'aktiviert':'deaktiviert').': '.$key;}
    public function ToggleFavoriteFor(string $key):string{$a=$this->IndexBy($this->ReadCsvAssoc('api_keys'),'api_key');if(!isset($a[$key]))return'API-Key nicht gefunden: '.$key;$a[$key]['is_favorite']=($a[$key]['is_favorite']??'0')==='1'?'0':'1';$this->WriteCsvAssoc('api_keys',array_values($a));$this->UpdateBrowserFormList($this->BuildBrowserRows());return'Favorit umgeschaltet: '.$key;}

    public function AssignApiKeyToDeviceFor(string $key,string $code,string $name,string $type,string $role):string{$key=trim($key);$code=trim($code);if($key===''||$code===''||!preg_match('/^[A-Za-z0-9_\-]+$/',$code))return'Ungueltiger API-Key oder Device-Code.';$a=$this->IndexBy($this->ReadCsvAssoc('api_keys'),'api_key');if(!isset($a[$key]))return'API-Key nicht gefunden: '.$key;$name=trim($name)?:$code;$type=trim($type)?:'sensor_group';$role=trim($role)?:'measurement';$now=date('Y-m-d H:i:s');$dev=$this->IndexBy($this->ReadCsvAssoc('devices'),'code');$old=$dev[$code]??[];$dev[$code]=['code'=>$code,'name'=>$name,'device_type'=>$type,'confidence'=>'100','status_key'=>$role==='status'?$key:($old['status_key']??''),'value_key'=>in_array($role,['value','measurement'],true)?$key:($old['value_key']??''),'first_seen'=>$old['first_seen']??$now,'last_seen'=>$now];$dk=array_values(array_filter($this->ReadCsvAssoc('device_keys'),fn($r)=>($r['api_key']??'')!==$key));$dk[]=['device_code'=>$code,'api_key'=>$key,'role'=>$role,'is_required'=>in_array($role,['status','value','measurement'],true)?'1':'0','direction'=>'read','assignment_source'=>'manual'];$this->WriteCsvAssoc('devices',array_values($dev));$this->WriteCsvAssoc('device_keys',$dk);$this->UpdateBrowserFormList($this->BuildBrowserRows());$this->UpdateDeviceFormList($this->BuildDeviceRows());return'Manuelle Device-Zuordnung gespeichert: '.$key.' -> '.$code.' ('.$role.').';}
    public function LoadDeviceDetailsFor(string $code):string{$dev=$this->IndexBy($this->ReadCsvAssoc('devices'),'code');if(!isset($dev[$code]))return'Device nicht gefunden: '.$code;$a=$this->IndexBy($this->ReadCsvAssoc('api_keys'),'api_key');$lines=[];foreach($this->ReadCsvAssoc('device_keys')as$k)if(($k['device_code']??'')===$code){$x=$a[$k['api_key']]??[];$lines[]=(($k['is_required']??'0')==='1'?'Pflicht':'Optional').' | '.($k['role']??'').' | '.($k['api_key']??'').' | Zuordnung: '.($k['assignment_source']??'auto').' | Import: '.(($x['gateway_import_enabled']??'0')==='1'?'ja':'nein').' | '.($x['current_value']??'').' | erkannt: '.($x['detected_value_type']??'').' | effektiv: '.($x['value_type']??'');}$d=$dev[$code];$out='Device: '.($d['name']??'')."\nCode: $code\nTyp: ".($d['device_type']??'')."\nVertrauen: ".($d['confidence']??'')."\nStatus-Key: ".($d['status_key']??'')."\nValue-Key: ".($d['value_key']??'')."\n\nKeys:\n".implode("\n",$lines);$this->SetValueSafe('SelectedDeviceDetails',$out);return$out;}
    public function PreviewDeviceExportFor(string $code):string{$dev=$this->IndexBy($this->ReadCsvAssoc('devices'),'code');if(!isset($dev[$code]))return'Device nicht gefunden: '.$code;$a=$this->IndexBy($this->ReadCsvAssoc('api_keys'),'api_key');$lines=[];foreach($this->ReadCsvAssoc('device_keys')as$k)if(($k['device_code']??'')===$code){$x=$a[$k['api_key']]??[];if(($x['gateway_import_enabled']??'0')!=='1')continue;$n=trim((string)($x['gateway_variable_name']??''))?:trim((string)($x['suggested_name']??''))?:($k['api_key']??'');$lines[]=($k['api_key']??'').' | Variable: '.$n.' | Typ: '.($x['value_type']??'').' | Semantik: '.($x['semantic_type']??'').' | Wert: '.($x['current_value']??'');}$d=$dev[$code];$out="Gateway Export-Vorschau\nDevice: ".($d['name']??'')."\nCode: $code\nAktivierte Variablen: ".count($lines)."\n\nVariablen:\n".(count($lines)?implode("\n",$lines):'[keine]');$this->SetValueSafe('DeviceExportPreview',$out);return$out;}

    private function DiscoverDeviceRangeFor(string $code,string $status,int $radius):string{$dev=$this->IndexBy($this->ReadCsvAssoc('devices'),'code');if(!isset($dev[$code]))return'Device nicht gefunden: '.$code;if(!preg_match('/^(\d+)\.(\d+)\.status$/',trim($status),$m))return'Ungueltiger Status-Key.';$g=(int)$m[1];$o=(int)$m[2];$s=array_values(array_unique(array_merge(['status','value','opmode','text1','text2'],$this->ParseSuffixes($this->ReadPropertyString('ScanSuffixes')))));$keys=[];for($i=max(1,$o-$radius);$i<=$o+$radius;$i++)foreach($s as$x)$keys[]="$g.$i.$x";try{$r=$this->ApiGet($keys);$data=$r['data']??[];if(!isset($data[$status]))return'Status-Key wurde vom PM5 nicht geliefert: '.$status;$a=$this->IndexBy($this->ReadCsvAssoc('api_keys'),'api_key');$dk=$this->ReadCsvAssoc('device_keys');$found=$assigned=$protected=0;$now=date('Y-m-d H:i:s');foreach($data as$k=>$v){$v=$this->CleanString((string)$v);if($v==='')continue;$found++;$md=$this->GetManualAssignmentDevice((string)$k,$dk);if($md!==''&&$md!==$code){$protected++;continue;}$d=$this->DetectValueType($v);$a[$k]=$this->MergeApiKeyObservation((string)$k,$v,$d,$a[$k]??[],$now,'');$dk=array_values(array_filter($dk,fn($x)=>($x['api_key']??'')!==$k));$role=$this->GetRoleForSuffix($this->GetKeySuffix((string)$k));$dk[]=['device_code'=>$code,'api_key'=>(string)$k,'role'=>$role,'is_required'=>in_array($role,['status','value','measurement'],true)?'1':'0','direction'=>'read','assignment_source'=>'manual'];$assigned++;}$dev[$code]['status_key']=$status;$dev[$code]['confidence']='100';$dev[$code]['last_seen']=$now;$vk="$g.$o.value";if(isset($a[$vk]))$dev[$code]['value_key']=$vk;$this->WriteCsvAssoc('api_keys',array_values($a));$this->WriteCsvAssoc('devices',array_values($dev));$this->WriteCsvAssoc('device_keys',$this->UniqueRows($dk,['device_code','api_key']));$this->UpdateBrowserFormList($this->BuildBrowserRows());$this->UpdateDeviceFormList($this->BuildDeviceRows());return($radius===0?'Device-Familie':'Device-Nachbarschaft Radius '.$radius).' abgeschlossen: '.$code.' | Status-Key: '.$status.' | getestet: '.count($keys).' | gefunden: '.$found.' | zugeordnet: '.$assigned.' | geschuetzt: '.$protected.'.';}catch(Throwable $e){return'Device-Familienfehler: '.$e->getMessage();}}

    private function MergeApiKeyObservation(string $k,string $v,string $d,array $e,string $now,string $sid):array{$ov=trim((string)($e['type_override']??''))?:'auto';return['api_key'=>$k,'current_value'=>$v,'detected_value_type'=>$d,'value_type'=>$this->ResolveEffectiveType($d,$ov),'type_override'=>$ov,'semantic_type'=>$e['semantic_type']??'','profile_override'=>$e['profile_override']??'','unit_override'=>$e['unit_override']??'','confidence'=>$e['confidence']??(string)$this->GetConfidence($k),'suggested_name'=>($e['suggested_name']??'')!==''?$e['suggested_name']:$this->GetKnownName($k),'is_favorite'=>$e['is_favorite']??'0','first_seen'=>$e['first_seen']??$now,'last_seen'=>$now,'last_scan_id'=>$sid!==''?$sid:($e['last_scan_id']??''),'comment'=>$e['comment']??'','gateway_variable_name'=>$e['gateway_variable_name']??'','gateway_import_enabled'=>$e['gateway_import_enabled']??'0'];}
    private function ResolveEffectiveType(string $d,string $o):string{if($o===''||$o==='auto')return$d;if($o==='boolean')return'boolean-candidate';if($o==='enum')return'integer';return$o;}
    private function UpdateApiKeyField(string $key,string $f,string $v,string $msg):string{$a=$this->IndexBy($this->ReadCsvAssoc('api_keys'),'api_key');if(!isset($a[$key]))return'API-Key nicht gefunden: '.$key;$a[$key][$f]=$v;$this->WriteCsvAssoc('api_keys',array_values($a));$this->UpdateBrowserFormList($this->BuildBrowserRows());return$msg.$key;}

    private function RegisterVariables():void{foreach([['StorageReady','CSV Storage bereit','~Switch',10,'bool'],['StorageStatus','CSV Storage Status','',20,'string'],['StoragePath','CSV Storage Pfad','',30,'string'],['StorageSchemaVersion','CSV Schema Version','',40,'int'],['LastScanId','Letzte Scan-ID','',100,'int'],['LastScanGeneratedKeys','Letzter Scan erzeugte Keys','',130,'int'],['LastScanFoundKeys','Letzter Scan Treffer','',140,'int'],['LastResponseTimeMs','Letzte API Antwortzeit gesamt','',150,'int'],['ScanSummary','Scan Zusammenfassung','',180,'string'],['BrowserSummary','Browser Zusammenfassung','',300,'string'],['SelectedApiKeyDetails','API-Key Details','',310,'string'],['SelectedDeviceDetails','Device Details','',410,'string'],['DeviceExportPreview','Device Export Vorschau','',420,'string']]as$v){if($v[4]==='bool')$this->RegisterVariableBoolean($v[0],$v[1],$v[2],$v[3]);elseif($v[4]==='int')$this->RegisterVariableInteger($v[0],$v[1],$v[2],$v[3]);else$this->RegisterVariableString($v[0],$v[1],$v[2],$v[3]);}}
    private function GetApiKeyListDefinition():array{return['type'=>'List','name'=>'BrowserList','caption'=>'API-Key Browser','rowCount'=>16,'add'=>false,'delete'=>false,'loadValuesFromConfiguration'=>false,'columns'=>array_map(fn($x)=>['name'=>$x[0],'caption'=>$x[1],'width'=>$x[2],'add'=>'','edit'=>false,'quickFilter'=>true],[['gateway_import','Import','60px'],['api_key','API-Key','160px'],['suggested_name','Name','130px'],['current_value','Wert','120px'],['detected_value_type','Erkannt','95px'],['value_type','Effektiv','90px'],['semantic_type','Semantik','100px'],['device','Device','110px'],['assignment_source','Zuordnung','80px'],['comment','Kommentar','170px']]),'values'=>$this->BuildBrowserRowsSafe()];}
    private function GetDeviceListDefinition():array{return['type'=>'List','name'=>'DeviceList','caption'=>'Device Browser','rowCount'=>10,'add'=>false,'delete'=>false,'loadValuesFromConfiguration'=>false,'columns'=>array_map(fn($x)=>['name'=>$x[0],'caption'=>$x[1],'width'=>$x[2],'add'=>'','edit'=>false],[['code','Code','130px'],['name','Name','160px'],['device_type','Typ','130px'],['confidence','Vertrauen','85px'],['key_count','Keys','60px'],['import_count','Import','60px'],['status_key','Status-Key','170px']]),'values'=>$this->BuildDeviceRowsSafe()];}
    private function BuildBrowserRowsSafe():array{try{return$this->BuildBrowserRows();}catch(Throwable $e){return[];}}private function BuildDeviceRowsSafe():array{try{return$this->BuildDeviceRows();}catch(Throwable $e){return[];}}
    private function BuildBrowserRows():array{$dev=$this->GetDeviceByKeyMap();$src=$this->GetAssignmentSourceByKeyMap();$r=[];foreach($this->ReadCsvAssoc('api_keys')as$x){$k=$x['api_key']??'';$r[]=['gateway_import'=>(($x['gateway_import_enabled']??'0')==='1'?'ja':''),'api_key'=>$k,'suggested_name'=>$x['suggested_name']??'','current_value'=>$x['current_value']??'','detected_value_type'=>$x['detected_value_type']??'','value_type'=>$x['value_type']??'','semantic_type'=>$x['semantic_type']??'','device'=>$dev[$k]??'','assignment_source'=>$src[$k]??'','comment'=>$x['comment']??'','last_seen'=>$x['last_seen']??''];}usort($r,fn($a,$b)=>strcmp($b['last_seen'],$a['last_seen']));return array_slice($r,0,250);}
    private function BuildDeviceRows():array{$c=[];$ic=[];$a=$this->IndexBy($this->ReadCsvAssoc('api_keys'),'api_key');foreach($this->ReadCsvAssoc('device_keys')as$d){$x=$d['device_code']??'';$k=$d['api_key']??'';if($x==='')continue;$c[$x]=($c[$x]??0)+1;if(($a[$k]['gateway_import_enabled']??'0')==='1')$ic[$x]=($ic[$x]??0)+1;}$r=[];foreach($this->ReadCsvAssoc('devices')as$d){$x=$d['code']??'';$r[]=['code'=>$x,'name'=>$d['name']??'','device_type'=>$d['device_type']??'','confidence'=>$d['confidence']??'','key_count'=>(string)($c[$x]??0),'import_count'=>(string)($ic[$x]??0),'status_key'=>$d['status_key']??''];}return$r;}
    private function BuildScanSummary():string{return'Scans: '.count($this->ReadCsvAssoc('scans')).', API-Keys: '.count($this->ReadCsvAssoc('api_keys')).', Beobachtungen: '.count($this->ReadCsvAssoc('observations')).', Devices: '.count($this->ReadCsvAssoc('devices'));}
    private function UpdateBrowserFormList(array $r):void{$this->UpdateFormField('BrowserList','values',json_encode($r,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?:'[]');}private function UpdateDeviceFormList(array $r):void{$this->UpdateFormField('DeviceList','values',json_encode($r,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?:'[]');}

    private function InitializeStorage():void{$dir=$this->GetStorageDirectory();if(!is_dir($dir)&&!mkdir($dir,0775,true)&&!is_dir($dir))throw new Exception('CSV-Verzeichnis konnte nicht erstellt werden: '.$dir);foreach(self::CSV_FILES as$n=>$h){$p=$this->GetCsvPath($n);if(!is_file($p))$this->WriteRawCsv($p,[$h]);else$this->EnsureCsvHeader($n);}$this->MigrateApiKeyTypes();$this->WriteCsvAssoc('meta',[['key'=>'schema_version','value'=>(string)self::SCHEMA_VERSION],['key'=>'version','value'=>'0.2.0-alpha']]);}
    private function MigrateApiKeyTypes():void{$r=$this->ReadCsvAssoc('api_keys');$ch=false;foreach($r as&$x){if(($x['detected_value_type']??'')===''){$x['detected_value_type']=$x['value_type']??'string';$ch=true;}if(($x['type_override']??'')===''){$x['type_override']='auto';$ch=true;}$e=$this->ResolveEffectiveType($x['detected_value_type'],$x['type_override']);if(($x['value_type']??'')!==$e){$x['value_type']=$e;$ch=true;}}unset($x);if($ch)$this->WriteCsvAssoc('api_keys',$r);}
    private function EnsureCsvHeader(string $n):void{$p=$this->GetCsvPath($n);$h=fopen($p,'rb');$old=$h?fgetcsv($h,0,';','"',''):[];if($h)fclose($h);if(count(array_diff(self::CSV_FILES[$n],is_array($old)?$old:[]))===0)return;$this->WriteCsvAssoc($n,$this->ReadCsvAssoc($n));}
    private function ReadCsvAssoc(string $n):array{$p=$this->GetCsvPath($n);if(!is_file($p))return[];$h=fopen($p,'rb');if(!$h)throw new Exception('CSV konnte nicht gelesen werden: '.$p);flock($h,LOCK_SH);$head=fgetcsv($h,0,';','"','');$r=[];if(is_array($head))while(($d=fgetcsv($h,0,';','"',''))!==false){$x=[];foreach($head as$i=>$k)$x[$k]=$d[$i]??'';if(implode('',$x)!=='')$r[]=$x;}flock($h,LOCK_UN);fclose($h);return$r;}
    private function WriteCsvAssoc(string $n,array $rows):void{$head=self::CSV_FILES[$n];$d=[$head];foreach($rows as$r)$d[]=array_map(fn($k)=>(string)($r[$k]??''),$head);$this->WriteRawCsv($this->GetCsvPath($n),$d);}private function AppendCsvAssoc(string $n,array $rows):void{if(!$rows)return;$h=fopen($this->GetCsvPath($n),'ab');flock($h,LOCK_EX);foreach($rows as$r){$l=[];foreach(self::CSV_FILES[$n]as$k)$l[]=(string)($r[$k]??'');fputcsv($h,$l,';','"','');}flock($h,LOCK_UN);fclose($h);}private function WriteRawCsv(string $p,array $rows):void{$t=$p.'.tmp';$h=fopen($t,'wb');foreach($rows as$r)fputcsv($h,$r,';','"','');fclose($h);if(!rename($t,$p))throw new Exception('CSV konnte nicht ersetzt werden: '.$p);}
    private function GetNextScanId():int{$m=0;foreach($this->ReadCsvAssoc('scans')as$s)$m=max($m,(int)($s['scan_id']??0));return$m+1;}

    private function ClassifyDevice(string $k,string $now,array &$dev,array &$dk):void{if($this->HasManualAssignment($k,$dk))return;if(strpos($k,'55.17106.')===0)$this->EnsureDevice('filter_pump','Filterpumpe','actuator',$k,$this->GetKeySuffix($k),$now,$dev,$dk);if(strpos($k,'55.17102.')===0)$this->EnsureDevice('pool_light','Poollicht','actuator',$k,$this->GetKeySuffix($k),$now,$dev,$dk);if(strpos($k,'34.')===0)$this->EnsureDevice('water_values','Wasserwerte','sensor_group',$k,'measurement',$now,$dev,$dk);if(strpos($k,'13.')===0)$this->EnsureDevice('system_values','Systemwerte','system_group',$k,'info',$now,$dev,$dk);}
    private function HasManualAssignment(string $k,array $dk):bool{foreach($dk as$r)if(($r['api_key']??'')===$k&&($r['assignment_source']??'auto')==='manual')return true;return false;}private function EnsureDevice(string $c,string $n,string $t,string $k,string $role,string $now,array &$dev,array &$dk):void{$e=$dev[$c]??[];$dev[$c]=['code'=>$c,'name'=>$n,'device_type'=>$t,'confidence'=>'80','status_key'=>$role==='status'?$k:($e['status_key']??''),'value_key'=>in_array($role,['value','measurement'],true)?$k:($e['value_key']??''),'first_seen'=>$e['first_seen']??$now,'last_seen'=>$now];$dk[]=['device_code'=>$c,'api_key'=>$k,'role'=>$role,'is_required'=>in_array($role,['status','value','measurement'],true)?'1':'0','direction'=>'read','assignment_source'=>'auto'];}
    private function ApiGet(array $keys):array{$host=trim($this->ReadPropertyString('Host'));if($host==='')throw new Exception('Host ist leer.');$url='http://'.$host.':'.max(1,min(65535,$this->ReadPropertyInteger('Port'))).'/cgi-bin/webgui.fcgi?sid='.rawurlencode($this->CreateSid());$p=json_encode(['get'=>array_values($keys)]);$ctx=stream_context_create(['http'=>['method'=>'POST','header'=>"Content-Type: application/json;charset=UTF-8\r\nAccept: application/json\r\n",'content'=>$p,'timeout'=>max(1,$this->ReadPropertyInteger('Timeout')),'ignore_errors'=>true]]);$st=microtime(true);$raw=@file_get_contents($url,false,$ctx);if($raw===false)throw new Exception('HTTP request failed.');$j=json_decode($raw,true);if(!is_array($j)||(int)($j['status']['code']??-1)!==0)throw new Exception('API Fehler.');$j['_meta']=['duration_ms'=>(int)round((microtime(true)-$st)*1000)];return$j;}
    private function BuildScanKeys():array{$r=[];$s=$this->ParseSuffixes($this->ReadPropertyString('ScanSuffixes'));$max=max(1,min(5000,$this->ReadPropertyInteger('ScanMaxKeys')));$firstGroup=max(1,min(999,$this->ReadPropertyInteger('ScanGroupStart')));$lastGroup=max($firstGroup,min(999,$this->ReadPropertyInteger('ScanGroupEnd')));foreach(self::DOCUMENTED_OBJECT_IDS as$g=>$objectIds){if($g<$firstGroup||$g>$lastGroup)continue;foreach($objectIds as$o)foreach($s as$x){$r[]="$g.$o.$x";if(count($r)>=$max)return$r;}}$firstObject=max(1,min(99999,$this->ReadPropertyInteger('ScanObjectStart')));$lastObject=max($firstObject,min(99999,$this->ReadPropertyInteger('ScanObjectEnd')));for($g=$firstGroup;$g<=$lastGroup;$g++){if(isset(self::DOCUMENTED_OBJECT_IDS[$g]))continue;for($o=$firstObject;$o<=$lastObject;$o++)foreach($s as$x){$r[]="$g.$o.$x";if(count($r)>=$max)return$r;}}return$r;}
    private function GetDeviceByKeyMap():array{$m=[];$src=[];foreach($this->ReadCsvAssoc('device_keys')as$d){$k=$d['api_key']??'';$s=$d['assignment_source']??'auto';if($k!==''&&(!isset($m[$k])||$s==='manual'||($src[$k]??'')!=='manual')){$m[$k]=$d['device_code']??'';$src[$k]=$s;}}return$m;}private function GetAssignmentSourceByKeyMap():array{$m=[];foreach($this->ReadCsvAssoc('device_keys')as$d){$k=$d['api_key']??'';$s=$d['assignment_source']??'auto';if($k!==''&&(!isset($m[$k])||$s==='manual'))$m[$k]=$s;}return$m;}private function GetManualAssignmentDevice(string $k,array $dk):string{foreach($dk as$r)if(($r['api_key']??'')===$k&&($r['assignment_source']??'auto')==='manual')return(string)($r['device_code']??'');return'';}private function GetRoleForSuffix(string $s):string{return$s==='status'?'status':($s==='value'?'value':($s==='opmode'?'opmode':'info'));}private function GetDeviceForApiKey(string $k):string{$m=$this->GetDeviceByKeyMap();return$m[$k]??'';}
    private function ParseSuffixes(string $r):array{$r=str_replace(["\r\n","\r",',',';'],"\n",$r);$o=[];foreach(explode("\n",$r)as$x){$x=trim($x);if($x!==''&&preg_match('/^[A-Za-z0-9_]+$/',$x))$o[$x]=$x;}return array_values($o?:['value']);}private function DetectValueType(string $v):string{$n=str_replace(',','.',$v);if($v==='0'||$v==='1')return'boolean-candidate';return is_numeric($n)?(strpos($n,'.')===false?'integer':'float'):'string';}private function GetConfidence(string $k):int{return in_array($k,['34.4001.value','34.4022.value','34.4033.value','13.16507.text2','13.16509.text1','55.17102.status','55.17102.value','55.17106.status','55.17106.opmode','55.17106.value'],true)?100:60;}private function GetKnownName(string $k):string{$n=['34.4001.value'=>'pH','34.4022.value'=>'Redox','34.4033.value'=>'Pooltemperatur','13.16507.text2'=>'Aussentemperatur T3','13.16509.text1'=>'Leitfaehigkeit','55.17106.status'=>'Filterpumpe Status','55.17106.opmode'=>'Filterpumpe Betriebsart','55.17106.value'=>'Filterpumpe Text','55.17102.status'=>'Poollicht Status','55.17102.value'=>'Poollicht Text'];return$n[$k]??'';}private function GetKeySuffix(string $k):string{$p=explode('.',$k);return(string)(end($p)?:'');}private function CleanString(string $v):string{return trim(html_entity_decode(strip_tags($v),ENT_QUOTES|ENT_HTML5,'UTF-8'));}private function CreateSid():string{return'SYMBAYROL'.substr(strtoupper(md5((string)microtime(true).mt_rand())),0,23);}private function IndexBy(array $r,string $k):array{$o=[];foreach($r as$x)if(($x[$k]??'')!=='')$o[$x[$k]]=$x;return$o;}private function UniqueRows(array $r,array $keys):array{$s=[];$o=[];foreach($r as$x){$p=[];foreach($keys as$k)$p[]=$x[$k]??'';$h=implode('|',$p);if(!isset($s[$h])){$s[$h]=1;$o[]=$x;}}return$o;}private function GetStorageDirectory():string{return rtrim(IPS_GetKernelDir(),DIRECTORY_SEPARATOR).DIRECTORY_SEPARATOR.'user'.DIRECTORY_SEPARATOR.'BayrolDiscovery';}private function GetCsvPath(string $n):string{return$this->GetStorageDirectory().DIRECTORY_SEPARATOR.$n.'.csv';}private function SetValueSafe(string $i,$v):void{$id=@$this->GetIDForIdent($i);if($id!==false&&$id>0)SetValue($id,$v);}
}
